version: '3.8'

services:
  app:
    container_name: LibraryApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db
  db:
    container_name: LibraryDB
    image: mongo:7.0.5
    restart: always
    ports:
      - "27017:27017"
    networks:
      - default
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

networks:
  default:
    driver: bridge
